[[_multi_tenancy]]
= Multi-tenancy support
:doctype: book
:sectnums:
:toc: left
:icons: font
:experimental:
:sourcedir: .

{this-platform} {this-application} is able to work in multi-tenant mode by connecting to a set of different SS7 operators.
The procedure is based on dividing of USSD routing rules into several areas ("subnetworks"). 

Each area has its unique digital "netwokId" value.
You can assign a unique USSD Global Title for each netwokId.
Each SS7 SCCP service access point (SAP) and each  USSD Routing Rule belongs to one of the networks (to each of them a networkId value is assigned). Default netwokId value is "0". If a user does not specify a netwokId value when USSD Routing Rule or SAP rule creation, networkId=0 will be assigned. 

When a PULL request comes from SS7 network, a networkId value from SAP will be assigned to a USSD dialog.
Then USSD Routing Rule with assigned networkId will be chosen for request routing to a proper HTTP or SIP application. 

When a PUSH request comes from HTTP application, a networkId value from HTTP XML payload ("networkId" attribute)  is taken (or is assigned as 0 if "networkId" attribute is missed in the XML payload). Then SS7 SAP will be chosen when routing USSD request to SS7 network. 

When a PUSH request comes from SIP application, a networkId value is always assigned as 0.
It is impossible now to use SIP App originated messages for multi-tenancy. 




NetworkId are specified at different places:

* for JSS7 level SAPs and SCCP routing rules are configured for this.
  See "7.4.5.
  Create a new Service Access Point" and "7.4.17.
  Create a new SCCP Rule" chapters of "JSS7 stack User Guide".
* for USSD Routing Rule see the chapter <<_setting_ussd_routing_rules_create>>.	

For configuring of USSD Global Titles - see chapters <<_setting_ussd_gt>>.
