[[_introduction]]
= Introduction to {this-platform} {this-application} 

{this-platform} {this-application} is an Open Source Java based USSD Gateway Platform that routes USSD messages from the signaling network to service applications and the other way around.
It enables operators to offer real-time interactions to mobile subscribers and deliver interactive content to their mobile phones. {this-platform} {this-application} strictly adheres to the standards and specifications defined by the International Telecommunications Union (ITU). 

{this-platform} {this-application} acts as an intermediary platform linking the service applications to the GSM network in a session oriented communication. The platform is easy-to-install and easy-to-deploy allowing you to have the Gateway set up and configured very quickly. 

{this-platform} {this-application} comes with an efficient Command Line Interface (CLI) tool allowing you to completely configure the Gateway at run-time and manage it using simple commands rather than do everything manually. {this-platform} {this-application} also comes with a Graphical User Interface (GUI) that will allow you to configure, monitor and manage the Gateway through a convenient user-friendly interface. 

The Open Source Software gives you the flexibility to understand the readily available source code and the freedom to customise the product to meet your Enterprise needs.

This guide provides details on configuring and using the platform and information regarding the supported protocols and compliant standards.
For installation instructions, please refer to the Installation Guide published along with this.
 
