[[_setup_downloading]]
= Downloading and Installing

Installing {this-platform} {this-application} is easy and quick with the binary download.
You can either download the binary release or download the source code and set up from source.

[[_downloading_binary]]
== Binary Download and Installation

The binary release is available for download at TeleStax Customer Support Portal &THIS.RELEASE_BINARY_URL;link: 

.Procedure: Binary Download and Installation
. Download the zip file `<filename>` to any folder of your choice. 
. Extract the contents of the zip file. 
+
----
Downloads]$ unzip <filename>
----						
+
. Verify the newly created directory and ensure the contents are as explained below.

[[_dir_structure]]
== Directory Structure

When you download the binary release, you will notice that the top level directory is named `{this-folder}-ussdgateway-<version>` and immediately below this are five sub-directories as explained below: 

* docs: Contains all relevant documentation in respective subfolders for JSLEE, jSS7, Management-HQ and USSD.
* jboss-5.1.0.GA: The core server with two profiles "default" and "simulator". The "default" profile is a clean profile where you will have to start from scratch and configure the entire SS7 Stack and USSD Gateway.
  The "simulator" profile is a pre-configured profile to work with jss7-simulator.
  Refer to the Admin Guide for instructions on how to start the server in either of the profiles.
* resources: Contains SLEE MAP, JDBC, http-client, http-servlet and SIP RA jars.
* tools: Contains SLEE tools and jss7-simulator.

[subs="attributes"]
----

|- {this-folder}-ussdgateway-<version>
		|- docs
				|+ jss7
				|+ slee
				|+ ussd
				|+ management-hq
		|- jboss-5.1.0.GA
				|+ bin    //contains start up and shutdown scripts for the Server and the start up script for Shell.
				|+ client
				|+ common
				|+ docs
				|+ lib
				|- server
					|+ default	//clean profile to set up from scratch
					|+ simulator	//pre-configured profile to work with the jss7-simulator
		|- resources
				|+ http-client
				|+ http-servlet
				|+ jdbc
				|+ map
		|- tools
				|+ eclipslee
				|+ jopr-plugin
				|+ remote-slee-connection
				|+ snmp
				|+ {this-folder}-jss7-simulator
				|+ {this-folder}-ussd-simulator
				|+ twiddle
----

[[_source_code]]
== Setup from Source 

{this-platform} {this-application} is an open source project and you have the freedom to build from source.
Building from source means you can stay on top with the latest features.
Whilst aspects of {this-platform} {this-application} are quite  complicated, you may find ways to become contributors.

{this-platform} {this-application} works with JDK1.7 or above.
In addition you must have the following tools installed.
 

* `Git Client` : Instructions for using GIT, including install, can be found at http://git-scm.com/book
* `Maven 3.2.X` : Instructions for using Maven, including install, can be found at http://maven.apache.org/
* `Ant 1.7.0` : Instructions for using Ant, including install, can be found at http://ant.apache.org


[[_source_building]]
=== Release Source Code Building


. Downloading the source code
+
Use GIT to checkout a specific release source, the base URL is &THIS.TRUNK_SOURCE_CODE_URL;, then add the specific release version. 
+
[source]
----

[usr]$ git clone &THIS.TRUNK_SOURCE_CODE_URL;
[usr]$ cd ussdgateway
[usr]$ git checkout <version>
----

. Building the source code
+
Now that we have the source the next step is to build and install the source.
 {this-platform} {this-application} uses Maven 2 to build the system.
You must ensure that `JAVA_HOME` environment variable is set properly prior to building the source.
+
[source]
----

[usr]$ mvn clean install
----


[[_trunk_source_building]]
=== Development Trunk Source Building

Similar process as for <<_source_building>>, the only change is don't switch to specific tag. 
