[[_setup_downloading]]
= Downloading and Installing

Installing {this-platform} {this-application} is easy and quick with the binary download.
You can either download the binary release or download the source code and set up from source.

[[_downloading_binary]]
== Binary Download and Installation

The binary release is available for download at the following link: {this-release-binary-url}

.Procedure: Binary Download and Installation
. Download the zip file `<filename>` to any folder of your choice. 
. Extract the contents of the zip file. 
+
----
Downloads]$ unzip <filename>
----						
+
. Verify the newly created directory and ensure the contents are as explained below.

[[_dir_structure]]
== Directory Structure (JBOSS 5)

When you download the binary release, you will notice that the top level directory is named `{this-folder}-ussdgateway-<version>` and immediately below this are five sub-directories as explained below: 

* docs: Contains all relevant documentation in respective subfolders for JSLEE, jSS7, Management-HQ and USSD.
* jboss-5.1.0.GA: The core server with two profiles "default" and "simulator". The "default" profile is a clean profile where you will have to start from scratch and configure the entire SS7 Stack and USSD Gateway.
  The "simulator" profile is a pre-configured profile to work with jss7-simulator.
  Refer to the Admin Guide for instructions on how to start the server in either of the profiles.
* resources: Contains SLEE MAP, JDBC, http-client, http-servlet and SIP RA jars.
* tools: Contains SLEE tools and jss7-simulator.

[subs="attributes"]
----

|- {this-folder}-ussdgateway-<version>
		|- docs
				|+ jss7
				|+ slee
				|+ ussd
				|+ management-hq
		|- jboss-5.1.0.GA
				|+ bin    //contains start up and shutdown scripts for the Server and the start up script for Shell.
				|+ client
				|+ common
				|+ docs
				|+ lib
				|- server
					|+ default	//clean profile to set up from scratch
					|+ simulator	//pre-configured profile to work with the jss7-simulator
		|- resources
				|+ http-client
				|+ http-servlet
				|+ jdbc
				|+ map
		|- tools
				|+ eclipslee
				|+ jopr-plugin
				|+ remote-slee-connection
				|+ snmp
				|+ {this-folder}-jss7-simulator
				|+ {this-folder}-ussd-simulator
				|+ twiddle
		|- template
				|+ META-INF-dialogic
				|+ META-INF-m3ua-dialogic
----

[[_dir_structure_wildfly]]
== Directory Structure (Wildfly)

When you download the binary release, you will notice that the top level directory is named `{this-folder}-ussdgateway-<version>` and immediately below this are five sub-directories as explained below: 

* docs: Contains all relevant documentation in respective subfolders for JSLEE, jSS7, Management-HQ and USSD.
* wildfly-10.1.0.Final: The core server with two profiles "standalone" and "simulator". The "standalone" profile is a clean profile where you will have to start from scratch and configure the entire SS7 Stack and USSD Gateway.
  The "simulator" profile is a pre-configured profile to work with jss7-simulator.
  Refer to the Admin Guide for instructions on how to start the server in either of the profiles.
* resources: Contains SLEE MAP, JDBC, http-client, http-servlet and SIP RA jars.
* tools: Contains SLEE tools and jss7-simulator.

[subs="attributes"]
----

|- {this-folder}-ussdgateway-<version>
		|- docs
				|+ jss7
				|+ slee
				|+ ussd
				|+ management-hq
		|- wildfly-10.1.0.Final
				|+ appclient
				|+ bin    //contains start up and shutdown scripts for the Server and the start up script for Shell.
				|+ docs
				|+ domain
				|+ lib
				|+ log
				|+ modules  //contains module binaries (including slee modules)
				|+ standalone //clean profile to set up from scratch
				|+ simulator	//pre-configured profile to work with the jss7-simulator
		|- resources
				|+ http-client
				|+ http-servlet
				|+ jdbc
				|+ map
		|- tools
				|+ eclipslee
				|+ jopr-plugin
				|+ remote-slee-connection
				|+ snmp
				|+ {this-folder}-jss7-simulator
				|+ {this-folder}-ussd-simulator
				|+ twiddle
		|- template
				|+ META-INF-dialogic
				|+ META-INF-m3ua-dialogic
----

[[_dialogic_setup]]
== Extra setup when usage of Dialogic cards

If you use only m3ua stack for communicating via SS7 network we can skip this chapter. If you use legacy dialogic cards with or without m3ua you need to follow actions from this chaper.

.Procedure: Extra actions for dialogic card usage
. Copy gct java lib: `gctApi.jar` from downloaded dialogic drivers (from folder `dpk/JAVA`) into the folder `jboss-5.1.0.GA/server/default/deploy/{this-folder}-ussd-gateway/lib`.
. Copy native lib: `libgctjni.so` from downloaded dialogic drivers (from folder `dpk/64` or `dpk/32` depending on JAVA 64 or 32-bit version) into the folder `jboss-5.1.0.GA/bin/META-INF/lib/linux2/x64` for JAVA 64-bit or `jboss-5.1.0.GA/bin/META-INF/lib/linux2/x86` for JAVA 32-bit.
. Copy jboss mbean config files: `jboss-beans.xml` and `jboss-structure.xml` files from `template/META-INF-dialogic` folder (if we use dialogic boards WITHOUT m3ua) or from `template/META-INF-m3ua-dialogic` folder (if we use dialogic boards WITH m3ua together) to folder `jboss-5.1.0.GA/server/default/deploy/{this-folder}-ussd-gateway/META-INF`
. In the copied `jboss-beans.xml` file you need to find a bean with DialogicMtp3UserPart class and update properties `sourceModuleId` and `destinationModuleId` with modules ids that are configured in your dialogc board.

[[_source_code]]
== Setup from Source 

{this-platform} {this-application} is an open source project and you have the freedom to build from source.
Building from source means you can stay on top with the latest features.
Whilst aspects of {this-platform} {this-application} are quite  complicated, you may find ways to become contributors.

{this-platform} {this-application} works with JDK1.7 or above.
In addition you must have the following tools installed.
 

* `Git Client` : Instructions for using GIT, including install, can be found at http://git-scm.com/book
* `Maven 3.2.X` : Instructions for using Maven, including install, can be found at http://maven.apache.org/
* `Ant 1.7.0` : Instructions for using Ant, including install, can be found at http://ant.apache.org


[[_source_building]]
=== Release Source Code Building


. Downloading the source code
+
Use GIT to checkout a specific release source, the base URL is {this-trunk-source-code-url}, then add the specific release version. 
+
[source]
[subs="attributes"]
----

[usr]$ git clone {this-trunk-source-code-url}.git
[usr]$ cd ussdgateway
[usr]$ git checkout <version>
----

. Building the source code
+
Now that we have the source the next step is to build and install the source.
 {this-platform} {this-application} uses Maven 2 to build the system.
You must ensure that `JAVA_HOME` environment variable is set properly prior to building the source.
+
[source]
----

[usr]$ mvn clean install
----


[[_trunk_source_building]]
=== Development Trunk Source Building

Similar process as for <<_source_building>>, the only change is don't switch to specific tag. 
